//import { select } from 'optimal-select/lib'

// this function detects if the id is generated by react framework
function isIDGeneratedByReact(id: string): boolean {
  return id.includes('__reactInternalInstance')
}

export function getPathTo(element: any): string | undefined {
  //   return select(element, {
  //     priority: ['id', 'class', 'href', 'src'],
  //     ignore: {
  //       class: (className: string) => {
  //         return className.length < 3
  //       },
  //     },
  //   })

  if (element.tagName === 'HTML' || element === document) return '/HTML[1]'
  if (element === document.body) return '/HTML[1]/BODY[1]'

  const elementId = element.id ?? ''
  if (elementId !== '' && !isIDGeneratedByReact(elementId)) return 'id("' + elementId + '")'

  let ix = 0
  const siblings = element.parentNode.childNodes
  for (let i = 0; i < siblings.length; i++) {
    const sibling = siblings[i]
    if (sibling === element)
      return getPathTo(element.parentNode) + '/' + element.tagName + '[' + (ix + 1) + ']'
    if (sibling.nodeType === 1 && sibling.tagName === element.tagName) ix++
  }
  return
}
