name: Syft Packages

on:
  push:
    branches: [release]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --include-dev
      - run: npx lerna run build
      - run: npx lerna run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: npm install --include-dev
      - run: npx lerna run build
      - run: cd packages/common;npm publish --access public;cd ../../;
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: cd packages/client;npm publish --access public;cd ../../;
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: cd packages/codehandler;npm publish --access public;cd ../../;
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: cd packages/next;npm publish --access public;cd ../../;
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      # - run: cd packages/test;npm publish --access public;cd ../../;
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: cd packages/cli;npm publish --access public;cd ../../;
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npx lerna bootstrap
  #     - run: npx lerna run build
  #     - run: cd packages/client;npm publish;cd ../../;
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #     - run: cd packages/cli;npm publish;cd ../../;
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # publish-cdn:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - run: npm ci
  #     - run: npx lerna run build-bundle @scope=@syftdata/reflector
  #     - run: node scripts/upload_gcs.js
  #       env:
  #         GCS_AUTH_TOKEN: ${{secrets.GCS_AUTH_TOKEN}}
  #         GCS_BUCKET_NAME: syftdata/cdn
